### ISSUE TITLE
'alias' changed in 2.0?

### ISSUE THREAD

**Issue by FredrikNoren** [jmreidy/grunt-browserify#167]
Hey, awesome plugin first of all! I'm using it for https://github.com/FredrikNoren/ungit

Anyway, tried upgrading to 2.0 and it seems like the 'alias' option has changed how it works, not sure if it's a bug or if the syntax has changed?

I had this which works fine in 1.3.2:

``` JSON
alias: [
          ...
          'knockout:',
          ...
        ]
```

Where knockout is a npm module I'm depending on.

In 2.0 it gives me this error:
Warning: Cannot find module '/home/travis/build/FredrikNoren/ungit/knockout' from '/home/travis/build/FredrikNoren/ungit' Use --force to continue.
