### ISSUE TITLE
require option not reading aliases from "browser" field of package.json in v3.3.0

### ISSUE THREAD

**Issue by baseten** [jmreidy/grunt-browserify#287]
After updating from v3.2.1 I began getting the following error message when trying to compile my library bundle:

    Warning: Cannot find module 'jquery' from 'path/to/project' Use --force to continue.

The relevant part of the Gruntfile.js configuration is as follows:

    browserify: {
        lib: {
            src: './path/to/src.js', 
            dest: './path/to/dest.js',
            options: {
                require: ['jquery']
            }
        }
    }

The src.js file only contains a single line `require('jquery')` although I get the error even when this line is removed so it seems to stem from the grunt config not the js.

The relevant part of the package.json is as follows:

    "browser": {
        "jquery": "./path/to/jquery.js"
    }

Library versions:
browserify v8.1.1
grunt-browserify v3.3.0
grunt v0.4.5
grunt-cli v0.1.13
node v0.10.35

**Comment by tleunen** [comment]
Not sure the `browser` field works with `browserify`...
But you could achieve the same thing by setting an alias.
```
browserify: {
    lib: {
        src: './path/to/src.js', 
        dest: './path/to/dest.js',
        options: {
            require: ['./path/to/jquery.js:jquery']
        }
    }
}
```
Since `grunt-browserify 3.2.0`, require and alias options are interchangeable

**Comment by baseten** [comment]
Browserify should honour the browser field as documented here:

https://github.com/substack/browserify-handbook/blob/master/readme.markdown#packagejson

It seems to be a new bug/issue with grunt-browserify as this exact setup
works with v3.2.1 but not in v3.3.0.

Is there a way to log out what is happening behind the scenes? I've tried
--verbose but it's not giving much more info.

Not sure the browser field works with browserify...
But you could achieve the same thing by setting an alias.

browserify: {
    lib: {
        src: './path/to/src.js',
        dest: './path/to/dest.js',
        options: {
            require: ['./path/to/jquery.js:jquery']
        }
    }
}

Since grunt-browserify 3.2.0, require and alias options are interchangeable

—
Reply to this email directly or view it on GitHub
<https://github.com/jmreidy/grunt-browserify/issues/287#issuecomment-71505622>
.

**Comment by tleunen** [comment]
Does it work with `browserify-cli`?

**Comment by tleunen** [comment]
Something tells me it doesn't work with `browserify-cli` either https://github.com/substack/node-browserify/issues/1072

**Comment by Gillingham** [comment]
This is an upstream bug as you've figured out, have the same issue using gulp/browserify.

**Comment by justinjmoses** [comment]
I'm in agreement with @baseten. Today I upgraded from browserify ~4 to 8 with no problems. I upgraded b-shim and hbsfy to their latest, nps. Then I tried grunt-browserify from 2.1.4 to latest and bang, same as above. It seems that even 3.0.0 has the same problem.

As with @baseten, I use b-shim `browserify` config in [package.json for aliases](https://github.com/thlorenz/browserify-shim#b-use-aliases). If I use the aliases as @tleunen suggests, it bundles fine, but then I have to deal with b-shim issues.

The issue referenced above - substack/node-browserify#1072 - seems related but I don't believe it is.

**Comment by justinjmoses** [comment]
I'm getting this problem even from 3.0.0 (just attempted to upgrade from 2.1.4 today). I've attempted to move my requires to use aliases, which worked, but now I'm stuck with my internal requires not being recognized when they don't contain aliases.

**Comment by sebbean** [comment]
any fix? or link?
